CREATE DATABASE AVENGERS;

USE AVENGERS;

CREATE TABLE HEROES (
	HERO_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
	HERO_NAME VARCHAR(50) NOT NULL,
    HERO_STATUS VARCHAR(25)
);

CREATE TABLE POWERS (
	POWER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	POWER_NAME VARCHAR(50) NOT NULL, 
    DESCRIPTION TEXT
);

CREATE TABLE HERO_POWERS (
	HERO_ID INT NOT NULL,
    POWER_ID INT NOT NULL,
    FOREIGN KEY (HERO_ID) REFERENCES HEROES(HERO_ID),
    FOREIGN KEY (POWER_ID) REFERENCES POWERS(POWER_ID),
    PRIMARY KEY (HERO_ID, POWER_ID)
);

COMMIT;